services:
  db:
    image: postgres:16
    container_name: andesfin_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: andesfin_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: andesfin_api
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: admin123
      DB_NAME: andesfin_db
    ports:
      - "3000:3000"

volumes:
  db_data:
